[versions]
kotlin = "2.0.20"
paper = "1.21-R0.1-SNAPSHOT"
shadow = "8.3.1"
exp4j = "0.4.8"
commons-math3 = "3.6.1"

[libraries]
# Kotlin libraries
#kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core-jvm", version = "1.9.0-RC.2" }

# Paper API
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }

# Math Evaluation
exp4j = { group = "net.objecthunter", name = "exp4j", version.ref = "exp4j" }
commons-math3 = { group = "org.apache.commons", name = "commons-math3", version.ref = "commons-math3" }
